---
name: iCal-Parser
version: 1.13
author:
  - 'Rick Frankel, cpan@rickster.com'
abstract: Parse iCalendar files into a data structure
license: perl
requires:
  DateTime::Format::ICal: 0.08
  File::Basename: 0
  IO::File: 1.1
  IO::String: 0
  Text::vFile::asData: 0.02
build_requires:
  FreezeThaw: 0.43
  Test::More: 0.54
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  iCal::Parser:
    file: lib/iCal/Parser.pm
    version: 1.13
resources:
  license: http://dev.perl.org/licenses/
